### ISSUE TITLE
Release v1.3

### ISSUE THREAD

**Issue by jameskbride** [crittercism/dexmaker#16]
Hi @dshirley, I'm curious what the timeline might be on releasing the next version of dexmaker?  I saw some activity a little over a week ago, but there hasn't been any update since then.  I know you're busy, and I appreciate your time.  Get back to me when you can.

Thanks!

**Comment by dshirley** [comment]
Hey @jameskbride I just applied for a new Maven Central GroupID.  I think this is the last blocker (knock on wood).  

According to Sonatype, it takes 2 business days to get a new maven repo created.

You can track the ticket here:  https://issues.sonatype.org/browse/OSSRH-15673

**Comment by jameskbride** [comment]
Great, thanks for the update!

**Comment by ened** [comment]
Here's my gradle.properties until dexmaker 1.3 is released:

```
# Testing dependencies.
ANDROID_TEST_VERSION = 0.2
# TODO: Upgrade, as soon as https://github.com/crittercism/dexmaker/issues/16 is pulled
DEXMAKER_VERSION = 1.2
ESPRESSO_VERSION = 2.1
HAMCREST_VERSION = 1.3
# Do not use JUnit 4.12, until Powermock can be upgraded to >1.6
JUNIT_VERSION = 4.11
# Raising Mockito version will java.lang.AbstractMethodError: abstract method not implemented until dexmaker can be
# upgraded to 1.3 (https://github.com/crittercism/dexmaker/pull/14 & https://github.com/crittercism/dexmaker/issues/16)
# the new version.
# MOCKITO_VERSION = 1.10.19
MOCKITO_VERSION = 1.9.5
OBJENESIS_VERSION = 1.3
# This must be in sync with the Mockito version, as Mockito X only works with Powermock Y.
# See this file: https://code.google.com/p/powermock/wiki/MockitoUsage13
POWERMOCK_VERSION = 1.5.6
ROBOLECTRIC_VERSION = 2.4
UIAUTOMATOR_VERSION = 2.1.0
```

So, `dexmaker` is the **key** to upgrading everything here. ;-)

**Comment by dshirley** [comment]
For some reason, the release is getting rejected from Sonatype.  It looks like other have received similar errors in the past and it looks like their issue was resolved by tech support at Sonatype.  Here's the issue if you'd like to track it:  https://issues.sonatype.org/browse/OSSRH-15744

**Comment by ened** [comment]
@dshirley looks like never-ending story. Have you tried the GPG solution?

**Comment by ened** [comment]
@dshirley maybe a deployment through a [github maven repo](http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github) would be better?

**Comment by dshirley** [comment]
That looks pretty promising.  I'll give it a shot tonight.

**Comment by ened** [comment]
@dshirley better not to make any promises on releasing dexmaker 1.3 any more.

Actually I'm surprised no-one else has nudged this project due to the issues both @jameskbride and I encountered.

@jameskbride is the problem with us? Are we doing things with dexmaker or powermockito that we are not supposed to be doing? Can we drop the dexmaker dependency altogether?

**Comment by jameskbride** [comment]
@ened I don't think we can simply drop it, as we need it in order to use Mockito/PowerMockito on a Dalvik JVM.  I don't think the Android community as a whole is very focused on testing though, so we're something of an edge case.  Personally I'd like to be able to use these tools to mock out my external dependencies, specifically the RESTful web services I'm currently working with.  If someone has a better suggestion on how to do this I'm all ears.

**Comment by dshirley** [comment]
@jameskbride For mocking out web services I think http://www.mock-server.com/ is probably what you want.  That's what we use for mocking out network calls.

**Comment by dshirley** [comment]
Ok, I finally got around to pushing out 1.3.
Sorry for the delay.

**Comment by dshirley** [comment]
Release instructions are in the commit message: f1ae6bd7d08974ee023d0904822100611617a213

**Comment by ened** [comment]
OMG, @dshirley thank you so much!

**Comment by ened** [comment]
@dshirley is there a slight chance that 1.3 is compiled against a older dexmaker version internally? Something that refers `com.google.dexmaker.dx.rop.type.Type` ?

**Comment by ened** [comment]
When downloading the current jar from I can find those references: 
`Lcom/google/dexmaker/dx/rop/type/Type;)Lcom/google/dexmaker/dx/rop/cst/CstType` and many more, however when I download dexmaker-dx, those classes are all in `com/android/dexmaker/dx`. @dshirley please check, thank you!

**Comment by dshirley** [comment]
The dexmaker/pom.xml uses jarjar to repackage some classes.  I think that's what you're pointing out:

https://github.com/crittercism/dexmaker/blob/master/dexmaker/pom.xml#L52

@ened Is this causing an issue or are you just curious what's going on?  If it is causing an issue, what is the impact of the issue?  Are fixes you expected are not there?  Are you hitting a runtime linking error?

Thanks,
-David

**Comment by ened** [comment]
@dshirley That is exactly the problem, as when a test is finally running on a device, the error messages are: 

```
com.company.view.SnappyGridLayoutManagerTest > testGetAvailableDistance[Product - 4.4.4] FAILED 
	java.lang.NoClassDefFoundError: com/google/dexmaker/stock/ProxyBuilder
	at com.google.dexmaker.mockito.DexmakerMockMaker.createMock(DexmakerMockMaker.java:55)
```

And this is because https://github.com/crittercism/dexmaker/blob/master/mockito/src/main/java/com/google/dexmaker/mockito/DexmakerMockMaker.java refers to the rewritten package.

So, could you re-package the dexmaker jar using jarjar as well and release 1.3.1?

**Comment by ened** [comment]
@dshirley see #18 for the same issue.. please help to correct it soon!

**Comment by nooone** [comment]
I'm facing an issue with 1.3 as well.

> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/dexmaker/dx/rop/type/Type;
at com.google.dexmaker.TypeId.<clinit>(TypeId.java:36)
at com.google.dexmaker.TypeId.get(TypeId.java:111)
at com.google.dexmaker.stock.ProxyBuilder.<clinit>(ProxyBuilder.java:758)
at com.google.dexmaker.mockito.DexmakerMockMaker.createMock(DexmakerMockMaker.java:55)
at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
at org.mockito.Mockito.spy(Mockito.java:1368)

**Comment by JessieAMorris** [comment]
I'm having this problem on 1.4 now. :-/
