### ISSUE TITLE
Inheritance?

### ISSUE THREAD

**Issue by mattiskan** [crittercism/dexmaker#9]
Is it possible to do inheritance with dexmaker?

I would like to create something like:
```
public class FOO extends BAR {
    public FOO( ) { }
}
```
I've gotten it working without the ```extends BAR``` part. I've read through tests and a little code, couldn't find an obvious way to do it. Is this possible?

**Comment by swankjesse** [comment]
Dexmaker.declare() accepts a superclass and interfaces.
